# Generated by Django 3.1.7 on 2021-03-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
