# Generated by Django 3.1.7 on 2021-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210311_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
