# Generated by Django 3.1.7 on 2021-03-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210311_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_account',
            field=models.IntegerField(default=0),
        ),
    ]
