# Generated by Django 3.1.7 on 2021-03-16 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210312_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='time_last_change_location',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 12, 38, 26, 496243)),
        ),
    ]
