# Generated by Django 3.1.7 on 2021-03-16 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210316_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_last_change_location',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 12, 44, 31, 498765)),
        ),
    ]
