# Generated by Django 3.1.7 on 2021-03-25 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210316_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_last_change_location',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 20, 29, 340692, tzinfo=utc)),
        ),
    ]
