# Generated by Django 3.1.7 on 2021-03-25 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210325_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_last_change_location',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 20, 53, 655824)),
        ),
    ]
