# Generated by Django 3.1.7 on 2021-03-28 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210328_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_last_change_location',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 15, 34, 33, 413778)),
        ),
    ]
