# Generated by Django 3.1.7 on 2021-03-30 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20210328_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_last_change_location',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 12, 35, 19, 831131)),
        ),
    ]
